services:
  - type: web
    name: podcast-app
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements-minimal.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120"
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
